name: Monitor SIGAA Activities

on:
  schedule:
    # Executa a cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permite execução manual

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        echo "Installing npm dependencies..."
        npm ci
        echo "Dependencies installed successfully"
        
    - name: Install additional Chrome dependencies
      run: |
        echo "Installing Chrome dependencies..."
        sudo apt-get update
        sudo apt-get install -y \
          fonts-liberation \
          libasound2t64 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libatspi2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libwayland-client0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxkbcommon0 \
          libxrandr2 \
          xdg-utils
        echo "Chrome dependencies installed successfully"
    
    - name: Create .env file
      run: |
        echo "SIGAA_USERNAME=${{ secrets.SIGAA_USERNAME }}" >> .env
        echo "SIGAA_PASSWORD=${{ secrets.SIGAA_PASSWORD }}" >> .env
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
        echo "HEADLESS=true" >> .env
        
    - name: Debug environment
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "Package.json scripts:"
        cat package.json | grep -A5 '"scripts"'
        
    - name: Run monitoring script
      run: |
        echo "Running monitoring script..."
        npm run monitor
      continue-on-error: false
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add last_activities.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update last activities data [skip ci]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
